# Generated by Django 5.2 on 2025-04-18 09:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TE', 'Tenant'), ('LA', 'Landlord'), ('BO', 'Both')], default='TE', help_text="User's primary role on the platform.", max_length=2)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number (e.g., +959xxxxxxxxx).', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, help_text='Contact address (distinct from property addresses).', null=True)),
                ('bio', models.TextField(blank=True, help_text='A short description about the user.', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text="User's profile picture.", null=True, upload_to='profile_pics/')),
                ('is_verified_landlord', models.BooleanField(default=False, help_text='Admin-verified status for landlords.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
