# Generated by Django 5.2 on 2025-04-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_populate_types_amenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order'], 'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='is_primary',
        ),
    ]
