# Generated by Django 5.2 on 2025-04-18 09:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The official start date of the lease term.')),
                ('end_date', models.DateField(help_text='The official end date of the lease term.')),
                ('status', models.CharField(choices=[('PE', 'Pending Approval'), ('AC', 'Active'), ('CO', 'Completed'), ('CA', 'Cancelled'), ('RE', 'Rejected')], default='PE', help_text='The current status of the lease agreement.', max_length=2)),
                ('monthly_rent_at_signing', models.DecimalField(decimal_places=2, help_text='Monthly rent amount agreed upon in the lease.', max_digits=12)),
                ('deposit_paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of the security deposit actually paid.', max_digits=12)),
                ('deposit_paid_date', models.DateField(blank=True, help_text='Date the deposit was paid.', null=True)),
                ('lease_document', models.FileField(blank=True, help_text='Optional scanned copy of the signed lease agreement.', null=True, upload_to='lease_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the lease record was created/application submitted.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(help_text='The property being leased.', on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.property')),
                ('tenant', models.ForeignKey(help_text='The user (Tenant) leasing the property.', on_delete=django.db.models.deletion.PROTECT, related_name='leases_held', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lease',
                'verbose_name_plural': 'Leases',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Overall rating from 1 (worst) to 5 (best).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Detailed review comment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.OneToOneField(help_text='The specific lease being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='leases.lease')),
                ('reviewer', models.ForeignKey(help_text='The user (Tenant) who wrote the review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='lease_end_date_gte_start_date'),
        ),
    ]
