# Generated by Django 5.2 on 2025-04-18 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Region or State (e.g., Yangon Region)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name.', max_length=110, unique=True)),
            ],
            options={
                'verbose_name': 'Region/State',
                'verbose_name_plural': 'Regions & States',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the City or District', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name.', max_length=110)),
                ('region_state', models.ForeignKey(help_text='The Region or State this district belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='locations.regionstate')),
            ],
            options={
                'verbose_name': 'City/District',
                'verbose_name_plural': 'Cities & Districts',
                'ordering': ['region_state', 'name'],
                'unique_together': {('name', 'region_state')},
            },
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Township (e.g., Dagon, Bahan)', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name.', max_length=110)),
                ('city_district', models.ForeignKey(help_text='The City or District this township belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='townships', to='locations.citydistrict')),
            ],
            options={
                'verbose_name': 'Township',
                'verbose_name_plural': 'Townships',
                'ordering': ['city_district', 'name'],
                'unique_together': {('name', 'city_district')},
            },
        ),
    ]
